package order.domain;

import order.constant.Consts;
import order.entity.Order;
import order.exceptions.ConditionError;
import order.exceptions.NotFoundException;
import order.model.request.CancelReqModel;
import order.model.request.OrderReqDetailsModel;
import order.model.request.UpdateReqModel;
import order.service.OrderRepository;
import org.springframework.beans.BeanUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.util.*;

@Component
public class OrderDomain {

    private static OrderRepository orderRepository;

    @Autowired
    public OrderDomain(OrderRepository orderRepository) {
        OrderDomain.orderRepository = orderRepository;
    }

    private static Date getDateNow() {
        return new java.util.Date();
    }


    public static void addOrder(Order order) {
        orderRepository.save(order);
        // activation params
        String side = ((order.getBuy()) ? "sale" : "buy");
        ComplexOrderDomain.activateByOtherOrder(order.getSymbol(), side, order.getQuantity());
    }

    public static Order prepareOrderObj(OrderReqDetailsModel req) {
        // order entity
        Order order = new Order();

        // copy properties from request params
        BeanUtils.copyProperties(req, order);

        // update order properties where need be to generated by system
        String orderId = UUID.randomUUID().toString();
        order.setOrderId(orderId);
        order.setOrderDate(getDateNow());
        order.setModifiedDate(getDateNow());
        order.setStatus(Consts.CONFIRMED);

        return order;
    }

    public static Order updateOrderQuantity(String orderId, UpdateReqModel req) {
        try {
            Order order = orderRepository.findById(orderId).get();
            if (order.getStatus().equals(Consts.CANCEL)){
                throw new ConditionError("Can not update cancelled order!");
            }
            order.setQuantity(req.getQuantity());
            order.setModifiedDate(getDateNow());
            orderRepository.save(order);
            return order;
        } catch (NoSuchElementException e) {
            throw new NotFoundException("id-" + orderId);
        }
    }

    public static Order cancelOrder(CancelReqModel req) {
        try {
            Order order = orderRepository.findById(req.getOrderId()).get();
            if (order.getStatus().equals(Consts.CANCEL)){
                throw new ConditionError("Order already cancelled!");
            }
            order.setStatus(Consts.CANCEL);
            order.setModifiedDate(getDateNow());
            orderRepository.save(order);
            return order;
        } catch (NoSuchElementException e) {
            throw new NotFoundException("id-" + req.getOrderId());
        }
    }

    public static Order getOrderById(String orderId) {
        try {
            return orderRepository.findById(orderId).get();
        } catch (NoSuchElementException e) {
            throw new NotFoundException("id-" + orderId);
        }
    }

    public static List<Order> getOrderByAccount(String account) {
        return orderRepository.findByAccount(account);
    }

    public static List<Order> findByAccountAndSymbol(String account, String symbol) {
        return orderRepository.findByAccountAndSymbol(account, symbol);
    }
}
